// Generated code from Butter Knife. Do not modify!
package com.ems.express.ui.send;

import android.view.View;
import butterknife.ButterKnife.Finder;
import butterknife.ButterKnife.Injector;

public class SendActivity$$ViewInjector<T extends com.ems.express.ui.send.SendActivity> implements Injector<T> {
  @Override public void inject(final Finder finder, final T target, Object source) {
    View view;
    view = finder.findRequiredView(source, 2131427618, "field 'mTvSenderName'");
    target.mTvSenderName = finder.castView(view, 2131427618, "field 'mTvSenderName'");
    view = finder.findRequiredView(source, 2131427632, "field 'mRbPayLater'");
    target.mRbPayLater = finder.castView(view, 2131427632, "field 'mRbPayLater'");
    view = finder.findRequiredView(source, 2131427651, "field 'mDatePicker'");
    target.mDatePicker = finder.castView(view, 2131427651, "field 'mDatePicker'");
    view = finder.findRequiredView(source, 2131427643, "field 'llDateTime'");
    target.llDateTime = finder.castView(view, 2131427643, "field 'llDateTime'");
    view = finder.findRequiredView(source, 2131427637, "field 'mTvExplainJifen'");
    target.mTvExplainJifen = finder.castView(view, 2131427637, "field 'mTvExplainJifen'");
    view = finder.findRequiredView(source, 2131427631, "field 'mRbPayNow'");
    target.mRbPayNow = finder.castView(view, 2131427631, "field 'mRbPayNow'");
    view = finder.findRequiredView(source, 2131427635, "field 'll4jifen'");
    target.ll4jifen = finder.castView(view, 2131427635, "field 'll4jifen'");
    view = finder.findRequiredView(source, 2131427641, "field 'mTvExplain'");
    target.mTvExplain = finder.castView(view, 2131427641, "field 'mTvExplain'");
    view = finder.findRequiredView(source, 2131427627, "field 'mWeightSelectionView'");
    target.mWeightSelectionView = finder.castView(view, 2131427627, "field 'mWeightSelectionView'");
    view = finder.findRequiredView(source, 2131427577, "field 'mEtWeight'");
    target.mEtWeight = finder.castView(view, 2131427577, "field 'mEtWeight'");
    view = finder.findRequiredView(source, 2131427638, "field 'mSendTypeSelectionView'");
    target.mSendTypeSelectionView = finder.castView(view, 2131427638, "field 'mSendTypeSelectionView'");
    view = finder.findRequiredView(source, 2131427649, "field 'mTvDateLine'");
    target.mTvDateLine = finder.castView(view, 2131427649, "field 'mTvDateLine'");
    view = finder.findRequiredView(source, 2131427620, "field 'mTvReceiverName'");
    target.mTvReceiverName = finder.castView(view, 2131427620, "field 'mTvReceiverName'");
    view = finder.findRequiredView(source, 2131427655, "field 'content'");
    target.content = finder.castView(view, 2131427655, "field 'content'");
    view = finder.findRequiredView(source, 2131427623, "field 'mWeightArrowView'");
    target.mWeightArrowView = finder.castView(view, 2131427623, "field 'mWeightArrowView'");
    view = finder.findRequiredView(source, 2131427439, "field 'mTvTime'");
    target.mTvTime = finder.castView(view, 2131427439, "field 'mTvTime'");
    view = finder.findRequiredView(source, 2131427538, "field 'jifenTotal'");
    target.jifenTotal = finder.castView(view, 2131427538, "field 'jifenTotal'");
    view = finder.findRequiredView(source, 2131427648, "field 'mTvDate'");
    target.mTvDate = finder.castView(view, 2131427648, "field 'mTvDate'");
    view = finder.findRequiredView(source, 2131427636, "field 'jifenUse'");
    target.jifenUse = finder.castView(view, 2131427636, "field 'jifenUse'");
    view = finder.findRequiredView(source, 2131427630, "field 'mPaymentSelectionView'");
    target.mPaymentSelectionView = finder.castView(view, 2131427630, "field 'mPaymentSelectionView'");
    view = finder.findRequiredView(source, 2131427633, "field 'mRbJifen'");
    target.mRbJifen = finder.castView(view, 2131427633, "field 'mRbJifen'");
    view = finder.findRequiredView(source, 2131427622, "field 'mSelectedWeight'");
    target.mSelectedWeight = finder.castView(view, 2131427622, "field 'mSelectedWeight'");
    view = finder.findRequiredView(source, 2131427634, "field 'line4youhui'");
    target.line4youhui = view;
    view = finder.findRequiredView(source, 2131427642, "field 'line4Time'");
    target.line4Time = view;
    view = finder.findRequiredView(source, 2131427628, "field 'mMailTypeSelectionView'");
    target.mMailTypeSelectionView = finder.castView(view, 2131427628, "field 'mMailTypeSelectionView'");
    view = finder.findRequiredView(source, 2131427987, "field 'mTvInfo'");
    target.mTvInfo = finder.castView(view, 2131427987, "field 'mTvInfo'");
    view = finder.findRequiredView(source, 2131427653, "field 'mRelayStatement'");
    target.mRelayStatement = finder.castView(view, 2131427653, "field 'mRelayStatement'");
    view = finder.findRequiredView(source, 2131427645, "field 'mSelecteDate'");
    target.mSelecteDate = finder.castView(view, 2131427645, "field 'mSelecteDate'");
    view = finder.findRequiredView(source, 2131427652, "field 'mTimePicker'");
    target.mTimePicker = finder.castView(view, 2131427652, "field 'mTimePicker'");
    view = finder.findRequiredView(source, 2131427654, "field 'mIvStatement'");
    target.mIvStatement = finder.castView(view, 2131427654, "field 'mIvStatement'");
    view = finder.findRequiredView(source, 2131427624, "field 'mBusinessTypeSelectionView'");
    target.mBusinessTypeSelectionView = finder.castView(view, 2131427624, "field 'mBusinessTypeSelectionView'");
    view = finder.findRequiredView(source, 2131427650, "field 'mTvTimeLine'");
    target.mTvTimeLine = finder.castView(view, 2131427650, "field 'mTvTimeLine'");
    view = finder.findRequiredView(source, 2131427646, "field 'mDateArrowView'");
    target.mDateArrowView = finder.castView(view, 2131427646, "field 'mDateArrowView'");
    view = finder.findRequiredView(source, 2131427647, "field 'mDateSelectionView'");
    target.mDateSelectionView = view;
  }

  @Override public void reset(T target) {
    target.mTvSenderName = null;
    target.mRbPayLater = null;
    target.mDatePicker = null;
    target.llDateTime = null;
    target.mTvExplainJifen = null;
    target.mRbPayNow = null;
    target.ll4jifen = null;
    target.mTvExplain = null;
    target.mWeightSelectionView = null;
    target.mEtWeight = null;
    target.mSendTypeSelectionView = null;
    target.mTvDateLine = null;
    target.mTvReceiverName = null;
    target.content = null;
    target.mWeightArrowView = null;
    target.mTvTime = null;
    target.jifenTotal = null;
    target.mTvDate = null;
    target.jifenUse = null;
    target.mPaymentSelectionView = null;
    target.mRbJifen = null;
    target.mSelectedWeight = null;
    target.line4youhui = null;
    target.line4Time = null;
    target.mMailTypeSelectionView = null;
    target.mTvInfo = null;
    target.mRelayStatement = null;
    target.mSelecteDate = null;
    target.mTimePicker = null;
    target.mIvStatement = null;
    target.mBusinessTypeSelectionView = null;
    target.mTvTimeLine = null;
    target.mDateArrowView = null;
    target.mDateSelectionView = null;
  }
}
