// Generated code from Butter Knife. Do not modify!
package com.ems.express.ui.send;

import android.view.View;
import butterknife.ButterKnife.Finder;
import butterknife.ButterKnife.Injector;

public class SendActivity$$ViewInjector<T extends com.ems.express.ui.send.SendActivity> implements Injector<T> {
  @Override public void inject(final Finder finder, final T target, Object source) {
    View view;
    view = finder.findRequiredView(source, 2131427571, "field 'mRbJifen'");
    target.mRbJifen = finder.castView(view, 2131427571, "field 'mRbJifen'");
    view = finder.findRequiredView(source, 2131427565, "field 'mWeightSelectionView'");
    target.mWeightSelectionView = finder.castView(view, 2131427565, "field 'mWeightSelectionView'");
    view = finder.findRequiredView(source, 2131427558, "field 'mTvReceiverName'");
    target.mTvReceiverName = finder.castView(view, 2131427558, "field 'mTvReceiverName'");
    view = finder.findRequiredView(source, 2131427378, "field 'mTvTime'");
    target.mTvTime = finder.castView(view, 2131427378, "field 'mTvTime'");
    view = finder.findRequiredView(source, 2131427583, "field 'mSelecteDate'");
    target.mSelecteDate = finder.castView(view, 2131427583, "field 'mSelecteDate'");
    view = finder.findRequiredView(source, 2131427568, "field 'mPaymentSelectionView'");
    target.mPaymentSelectionView = finder.castView(view, 2131427568, "field 'mPaymentSelectionView'");
    view = finder.findRequiredView(source, 2131427569, "field 'mRbPayNow'");
    target.mRbPayNow = finder.castView(view, 2131427569, "field 'mRbPayNow'");
    view = finder.findRequiredView(source, 2131427572, "field 'line4youhui'");
    target.line4youhui = view;
    view = finder.findRequiredView(source, 2131427573, "field 'll4jifen'");
    target.ll4jifen = finder.castView(view, 2131427573, "field 'll4jifen'");
    view = finder.findRequiredView(source, 2131427580, "field 'line4Time'");
    target.line4Time = view;
    view = finder.findRequiredView(source, 2131427562, "field 'mBusinessTypeSelectionView'");
    target.mBusinessTypeSelectionView = finder.castView(view, 2131427562, "field 'mBusinessTypeSelectionView'");
    view = finder.findRequiredView(source, 2131427590, "field 'mTimePicker'");
    target.mTimePicker = finder.castView(view, 2131427590, "field 'mTimePicker'");
    view = finder.findRequiredView(source, 2131427587, "field 'mTvDateLine'");
    target.mTvDateLine = finder.castView(view, 2131427587, "field 'mTvDateLine'");
    view = finder.findRequiredView(source, 2131427477, "field 'jifenTotal'");
    target.jifenTotal = finder.castView(view, 2131427477, "field 'jifenTotal'");
    view = finder.findRequiredView(source, 2131427570, "field 'mRbPayLater'");
    target.mRbPayLater = finder.castView(view, 2131427570, "field 'mRbPayLater'");
    view = finder.findRequiredView(source, 2131427586, "field 'mTvDate'");
    target.mTvDate = finder.castView(view, 2131427586, "field 'mTvDate'");
    view = finder.findRequiredView(source, 2131427566, "field 'mMailTypeSelectionView'");
    target.mMailTypeSelectionView = finder.castView(view, 2131427566, "field 'mMailTypeSelectionView'");
    view = finder.findRequiredView(source, 2131427556, "field 'mTvSenderName'");
    target.mTvSenderName = finder.castView(view, 2131427556, "field 'mTvSenderName'");
    view = finder.findRequiredView(source, 2131427591, "field 'mRelayStatement'");
    target.mRelayStatement = finder.castView(view, 2131427591, "field 'mRelayStatement'");
    view = finder.findRequiredView(source, 2131427560, "field 'mSelectedWeight'");
    target.mSelectedWeight = finder.castView(view, 2131427560, "field 'mSelectedWeight'");
    view = finder.findRequiredView(source, 2131427589, "field 'mDatePicker'");
    target.mDatePicker = finder.castView(view, 2131427589, "field 'mDatePicker'");
    view = finder.findRequiredView(source, 2131427584, "field 'mDateArrowView'");
    target.mDateArrowView = finder.castView(view, 2131427584, "field 'mDateArrowView'");
    view = finder.findRequiredView(source, 2131427592, "field 'mIvStatement'");
    target.mIvStatement = finder.castView(view, 2131427592, "field 'mIvStatement'");
    view = finder.findRequiredView(source, 2131427561, "field 'mWeightArrowView'");
    target.mWeightArrowView = finder.castView(view, 2131427561, "field 'mWeightArrowView'");
    view = finder.findRequiredView(source, 2131427574, "field 'jifenUse'");
    target.jifenUse = finder.castView(view, 2131427574, "field 'jifenUse'");
    view = finder.findRequiredView(source, 2131427581, "field 'llDateTime'");
    target.llDateTime = finder.castView(view, 2131427581, "field 'llDateTime'");
    view = finder.findRequiredView(source, 2131427579, "field 'mTvExplain'");
    target.mTvExplain = finder.castView(view, 2131427579, "field 'mTvExplain'");
    view = finder.findRequiredView(source, 2131427593, "field 'content'");
    target.content = finder.castView(view, 2131427593, "field 'content'");
    view = finder.findRequiredView(source, 2131427515, "field 'mEtWeight'");
    target.mEtWeight = finder.castView(view, 2131427515, "field 'mEtWeight'");
    view = finder.findRequiredView(source, 2131427852, "field 'mTvInfo'");
    target.mTvInfo = finder.castView(view, 2131427852, "field 'mTvInfo'");
    view = finder.findRequiredView(source, 2131427576, "field 'mSendTypeSelectionView'");
    target.mSendTypeSelectionView = finder.castView(view, 2131427576, "field 'mSendTypeSelectionView'");
    view = finder.findRequiredView(source, 2131427585, "field 'mDateSelectionView'");
    target.mDateSelectionView = view;
    view = finder.findRequiredView(source, 2131427575, "field 'mTvExplainJifen'");
    target.mTvExplainJifen = finder.castView(view, 2131427575, "field 'mTvExplainJifen'");
    view = finder.findRequiredView(source, 2131427588, "field 'mTvTimeLine'");
    target.mTvTimeLine = finder.castView(view, 2131427588, "field 'mTvTimeLine'");
  }

  @Override public void reset(T target) {
    target.mRbJifen = null;
    target.mWeightSelectionView = null;
    target.mTvReceiverName = null;
    target.mTvTime = null;
    target.mSelecteDate = null;
    target.mPaymentSelectionView = null;
    target.mRbPayNow = null;
    target.line4youhui = null;
    target.ll4jifen = null;
    target.line4Time = null;
    target.mBusinessTypeSelectionView = null;
    target.mTimePicker = null;
    target.mTvDateLine = null;
    target.jifenTotal = null;
    target.mRbPayLater = null;
    target.mTvDate = null;
    target.mMailTypeSelectionView = null;
    target.mTvSenderName = null;
    target.mRelayStatement = null;
    target.mSelectedWeight = null;
    target.mDatePicker = null;
    target.mDateArrowView = null;
    target.mIvStatement = null;
    target.mWeightArrowView = null;
    target.jifenUse = null;
    target.llDateTime = null;
    target.mTvExplain = null;
    target.content = null;
    target.mEtWeight = null;
    target.mTvInfo = null;
    target.mSendTypeSelectionView = null;
    target.mDateSelectionView = null;
    target.mTvExplainJifen = null;
    target.mTvTimeLine = null;
  }
}
