/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.allthingschat;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
    }
    public static final class drawable {
        public static final int add=0x7f020000;
        public static final int add_big=0x7f020001;
        public static final int add_comment=0x7f020002;
        public static final int back=0x7f020003;
        public static final int buttonstyle=0x7f020004;
        public static final int chatfriend=0x7f020005;
        public static final int chatmore=0x7f020006;
        public static final int collect=0x7f020007;
        public static final int collect_down=0x7f020008;
        public static final int conmment=0x7f020009;
        public static final int dialog_confirm_selected=0x7f02000a;
        public static final int friend=0x7f02000b;
        public static final int horizontal_line=0x7f02000c;
        public static final int ic_launcher=0x7f02000d;
        public static final int iconfont_yanjing=0x7f02000e;
        public static final int iconfont_zhaopian=0x7f02000f;
        public static final int index=0x7f020010;
        public static final int index_down=0x7f020011;
        public static final int install=0x7f020012;
        public static final int labelclassify_left_select=0x7f020013;
        public static final int mood=0x7f020014;
        public static final int more=0x7f020015;
        public static final int more_bottom=0x7f020016;
        public static final int more_top=0x7f020017;
        public static final int my=0x7f020018;
        public static final int my_down=0x7f020019;
        public static final int p1=0x7f02001a;
        public static final int p2=0x7f02001b;
        public static final int p3=0x7f02001c;
        public static final int p4=0x7f02001d;
        public static final int p5=0x7f02001e;
        public static final int p6=0x7f02001f;
        public static final int partake=0x7f020020;
        public static final int praise=0x7f020021;
        public static final int qq=0x7f020022;
        public static final int qqzone=0x7f020023;
        public static final int release=0x7f020024;
        public static final int release_down=0x7f020025;
        public static final int report=0x7f020026;
        public static final int send_comment=0x7f020027;
        public static final int shape=0x7f020028;
        public static final int shape_dialog_circle=0x7f020029;
        public static final int tab_collect_select=0x7f02002a;
        public static final int tab_index_select=0x7f02002b;
        public static final int tab_my_select=0x7f02002c;
        public static final int tab_release_select=0x7f02002d;
        public static final int top=0x7f02002e;
        public static final int transmit=0x7f02002f;
        public static final int userfullauguage=0x7f020030;
        public static final int weichat=0x7f020031;
    }
    public static final class id {
        public static final int action_settings=0x7f080047;
        public static final int add=0x7f080046;
        public static final int add_firend=0x7f08003e;
        public static final int age=0x7f08002e;
        public static final int bottoms=0x7f080002;
        public static final int coll_list=0x7f080018;
        public static final int collect=0x7f080006;
        public static final int dialog_cancel=0x7f080020;
        public static final int dialog_content=0x7f080023;
        public static final int dialog_determine=0x7f08001f;
        public static final int dialog_title2=0x7f080021;
        public static final int et_search=0x7f08003f;
        public static final int ib=0x7f08001a;
        public static final int ib1=0x7f08001b;
        public static final int ib2=0x7f08001c;
        public static final int ib3=0x7f08001d;
        public static final int ib5=0x7f08001e;
        public static final int ib_head=0x7f080011;
        public static final int index=0x7f080003;
        public static final int iv=0x7f080024;
        public static final int iv1=0x7f080029;
        public static final int iv2=0x7f08002f;
        public static final int iv3=0x7f080030;
        public static final int iv4=0x7f080031;
        public static final int iv5=0x7f080032;
        public static final int iv6=0x7f080033;
        public static final int iv_b1=0x7f080004;
        public static final int iv_b2=0x7f080007;
        public static final int iv_b3=0x7f08000a;
        public static final int iv_b4=0x7f08000d;
        public static final int iv_head=0x7f08002d;
        public static final int iv_pic=0x7f080019;
        public static final int line=0x7f080010;
        public static final int line_1=0x7f080022;
        public static final int ll=0x7f080015;
        public static final int ll1=0x7f080016;
        public static final int ll2=0x7f080017;
        public static final int ll_content=0x7f080001;
        public static final int lv=0x7f08002b;
        public static final int lv2=0x7f08002c;
        public static final int more=0x7f080026;
        public static final int my=0x7f08000c;
        public static final int mytalking_title=0x7f080034;
        public static final int name=0x7f080012;
        public static final int partake_title=0x7f080027;
        public static final int re=0x7f080025;
        public static final int release=0x7f080009;
        public static final int remove=0x7f080044;
        public static final int rl=0x7f08000f;
        public static final int rl1=0x7f080028;
        public static final int sv=0x7f08002a;
        public static final int tab_collect=0x7f080041;
        public static final int tab_index=0x7f080040;
        public static final int tab_my=0x7f080043;
        public static final int tab_release=0x7f080042;
        public static final int title=0x7f080000;
        public static final int titles=0x7f080045;
        public static final int tv=0x7f080014;
        public static final int tv1=0x7f080013;
        public static final int tv2=0x7f080035;
        public static final int tv3=0x7f080036;
        public static final int tv4=0x7f080037;
        public static final int tv_1=0x7f080038;
        public static final int tv_2=0x7f080039;
        public static final int tv_3=0x7f08003a;
        public static final int tv_4=0x7f08003b;
        public static final int tv_5=0x7f08003c;
        public static final int tv_6=0x7f08003d;
        public static final int tv_b1=0x7f080005;
        public static final int tv_b2=0x7f080008;
        public static final int tv_b3=0x7f08000b;
        public static final int tv_b4=0x7f08000e;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int add_actvivty=0x7f030001;
        public static final int alltalking_listview_items=0x7f030002;
        public static final int channel_activivty=0x7f030003;
        public static final int collect_activity=0x7f030004;
        public static final int collect_listview_items=0x7f030005;
        public static final int dialog_bottom=0x7f030006;
        public static final int dialog_confirm=0x7f030007;
        public static final int index_activity=0x7f030008;
        public static final int ipartake_activity=0x7f030009;
        public static final int ipartake_titile=0x7f03000a;
        public static final int labelclassify_activity=0x7f03000b;
        public static final int labelclassify_left_items=0x7f03000c;
        public static final int labelclassify_right_items=0x7f03000d;
        public static final int line=0x7f03000e;
        public static final int my_activity=0x7f03000f;
        public static final int mytalking_activity=0x7f030010;
        public static final int mytalking_title=0x7f030011;
        public static final int personol_activity=0x7f030012;
        public static final int sendcomment_bottom=0x7f030013;
        public static final int tabmini=0x7f030014;
        public static final int title=0x7f030015;
    }
    public static final class menu {
        public static final int main=0x7f070000;
    }
    public static final class string {
        public static final int action_settings=0x7f050002;
        public static final int app_name=0x7f050000;
        public static final int hello_world=0x7f050001;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060003;
        public static final int DialogStyle4=0x7f060002;
        public static final int line_margin_no=0x7f060001;
    }
}
